name: project_environment
channels:
- anaconda
- conda-forge
dependencies:
- python=3.7.9
#- pip=20.2.4
- pip:
  - azureml-train-automl-runtime==1.40.0.post1
  - inference-schema
  - azureml-interpret==1.40.0
  - azureml-defaults==1.40.0
- numpy~=1.18.0
- scikit-learn==0.22.1
- pandas~=1.1.5
- py-xgboost==1.3.3
- fbprophet==0.7.1
- holidays==0.10.3
- psutil>5.0.0,<6.0.0
